version: '3.4'

x-common-variables: &common-variables
  ORACLE_USER: DEMENTEV_MAO[PxU_DCBUL_UMA_MOD]
  ORACLE_PASSWORD: Toyota06#
  ORACLE_TNS: DATALAB
  NLS_LANG: AMERICAN_AMERICA.AL32UTF8

services:
  reports_server:
    restart: unless-stopped
    image: reports_server:latest
    container_name: reports_server_flask
    environment:
      <<: *common-variables
      POTRFOLIO_TABLE: leo_dinam_portf
      SERVICE_PORT: 80
      GUNICORN_TIMEOUT: 60
      SERVICE_WORKERS: 3
      SERVICE_THREADS: 3
    volumes:
      - ./tnsnames.ora:/usr/lib/oracle/19.5/client64/lib/network/admin/tnsnames.ora:ro

  web_server:
    restart: unless-stopped
    image: nginx:latest
    container_name: reports_server_nginx
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - 80:80
    - 443:443
