version: '3.4'

x-common-variables: &common-variables
  ORACLE_USER:
  ORACLE_PASSWORD:
  ORACLE_TNS:
  NLS_LANG: AMERICAN_AMERICA.AL32UTF8

services:
  reports_server:
    restart: unless-stopped
    image: reports_server:latest
    container_name: reports_server_flask
    environment:
      <<: *common-variables
      POTRFOLIO_TABLE: leo_dinam_portf
      SERVICE_PORT: 80
      GUNICORN_TIMEOUT: 60
      SERVICE_WORKERS: 3
      SERVICE_THREADS: 3
    volumes:
      - ./tnsnames.ora:/usr/lib/oracle/19.5/client64/lib/network/admin/tnsnames.ora:ro

  web_server:
    restart: unless-stopped
    image: nginx:latest
    container_name: reports_server_nginx
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs/:ro
    ports:
    - 443:443